(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const store='leavitt-presentation-v2';
const profile={company:'The Leavitt Group',rep:'Aidan Leavitt',role:'Home Energy Consultant',bio:'I help homeowners compare their current utility path against a custom solar plan built around their usage, roof, and long-term savings goals.',proofLink:'',accent:'#f4c76b',logo:'',photo:'',...JSON.parse(localStorage.getItem(store)||'{}')};
const touched=new Set();
const programs={
aps:['APS','TOU battery strategy','Store solar and reduce higher-cost evening usage. Verify current APS rate plan before final proposal.',65,0,0,10,'Rate plans and program rules can change. A home survey keeps the project moving while the current plan is still available.'],
srp:['SRP','Demand + TOU battery strategy','Reduce peak demand exposure and shift stored solar into higher-cost windows. Verify the exact SRP price plan before final proposal.',75,0,0,10,'Battery sizing should be matched to the right SRP plan. Survey is the next clean step.'],
sce:['SCE','SGIP battery incentive review','SGIP may provide storage incentives when eligibility and budget rules are met. Final availability must be verified through SGIP/program administrator.',70,150,1100,10,'SGIP budgets and steps can move. Verify eligibility and reserve the project path before funding changes.'],
iid:['IID','Low-export battery strategy','Battery value is strongest when export credits are low and stored solar can be used later in the home instead of sent back cheap.',85,0,0,10,'Battery sizing matters here. Delaying can mean continuing to export extra solar for less than the value of using it yourself.'],
cmp:['CMP','Backup + self-consumption review','Battery value is mainly backup power, solar self-consumption, and rate protection. Verify current Maine options before final proposal.',35,0,0,10,'Survey confirms whether backup storage makes sense for the home.'],
versant:['Versant','Backup + self-consumption review','Battery value is mainly backup power, solar self-consumption, and rate protection. Verify current Maine options before final proposal.',35,0,0,10,'Survey confirms whether backup storage makes sense for the home.']
};
const money=n=>(Number(n)||0).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0});
const val=(id,d='')=>$('#'+id)?.value?.trim()||d;
const put=(id,t)=>{const e=$('#'+id);if(e)e.textContent=t};
const pains=()=>$$('#painChecks input:checked').map(i=>i.value);
const toast=t=>{const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1300)};
function injectStyle(){let s=document.createElement('style');s.textContent=`body.tabbed-presentation{padding-top:76px;padding-bottom:104px}.topbar{position:fixed!important;top:0;left:0;right:0;z-index:1000;box-shadow:0 18px 45px rgba(0,0,0,.28)}.stage-hidden{display:none!important}.nav a.active{background:var(--gold,#f4c76b)!important;border-color:var(--gold,#f4c76b)!important;color:#090805!important}.deal-bar.empty .hero-actions,.deal-bar.empty strong{display:none}.deal-bar.empty{justify-content:flex-start}.deal-bar.empty small:after{content:'  Add details as you go';color:#8f887d;font-weight:700;margin-left:8px}.mini-program{margin-top:14px}.urgency-line{border-left:3px solid var(--gold,#f4c76b);padding-left:12px;color:#fbf6ea!important}.equity-row{display:flex!important;flex-direction:row!important;align-items:center;gap:10px}.equity-row input{width:auto;min-height:auto}.printing-all .stage-hidden{display:block!important}.printing-all .topbar,.printing-all .deal-bar,.printing-all .settings,.printing-all .toast{display:none!important}@media print{body{padding:0!important;background:#fff!important;color:#111!important}.stage-hidden{display:block!important}.topbar,.deal-bar,.settings,.toast{display:none!important}main>section{display:block!important;page-break-inside:avoid}.panel,.slide,.device-card,.cards article,.timeline article,.results article,.metric-grid article,.mini-grid article{box-shadow:none!important;background:#fff!important;color:#111!important;border-color:#ddd!important}.muted,p{color:#333!important}}@media(max-width:900px){body.tabbed-presentation{padding-top:118px}.topbar-inner{height:auto!important;min-height:0!important;flex-wrap:wrap;padding-top:8px!important;padding-bottom:8px!important}.nav{display:flex!important;order:3;width:100%;overflow-x:auto;padding-bottom:2px}.nav a{flex:0 0 auto}.brand{min-width:0;flex:1}.brand small{display:none}.topbar .button{flex:0 0 auto}.deal-bar.has-details{align-items:flex-start}}@media(max-width:520px){body.tabbed-presentation{padding-top:112px}.nav a{font-size:11px;padding:9px 10px}.deal-bar .hero-actions{display:grid;grid-template-columns:1fr 1fr;width:100%}.deal-bar .button{width:100%}}`;document.head.appendChild(s)}
function applyProfile(){document.documentElement.style.setProperty('--gold',profile.accent);$$('[data-company]').forEach(e=>e.textContent=profile.company);$$('[data-rep]').forEach(e=>e.textContent=profile.rep);$$('[data-role]').forEach(e=>e.textContent=profile.role);['company','rep','role','bio','proofLink','accent'].forEach(k=>{let id=k+'Input',e=$('#'+id);if(e)e.value=profile[k]||''});put('bioOutput',profile.bio);$$('[data-logo]').forEach(e=>e.innerHTML=profile.logo?`<img alt="Company logo" src="${profile.logo}">`:'LG');$$('[data-photo]').forEach(e=>e.innerHTML=profile.photo?`<img alt="Consultant photo" src="${profile.photo}">`:'');let p=$('#proofLink');if(p){p.hidden=!profile.proofLink;p.href=profile.proofLink||'#'}}
function saveProfile(){profile.company=val('companyInput','The Leavitt Group');profile.rep=val('repInput','Aidan Leavitt');profile.role=val('roleInput','Home Energy Consultant');profile.bio=val('bioInput',profile.bio);profile.proofLink=val('proofLinkInput','');profile.accent=$('#accentInput')?.value||'#f4c76b';localStorage.setItem(store,JSON.stringify(profile));applyProfile();toast('Saved')}
function addFields(){
$('#fullscreenButton')?.remove();
let print=$$('button').find(b=>(b.textContent||'').toLowerCase().includes('print snapshot'));if(print){print.removeAttribute('onclick');print.id='printSnapshotButton'}
let addr=$('#customerAddress')?.closest('label');if(addr&&!$('#siteSurveyDate'))addr.insertAdjacentHTML('afterend','<label>Site survey date<input id="siteSurveyDate" type="date"></label>');
let calc=$('.calc-inputs');if(calc&&!$('#utilityInput'))calc.insertAdjacentHTML('beforeend',`<label>Utility / battery program<select id="utilityInput"><option value="aps">APS</option><option value="srp">SRP</option><option value="sce">SCE / SGIP</option><option value="iid">IID</option><option value="cmp">CMP</option><option value="versant">Versant</option></select></label><label>Battery size kWh<input id="batteryKwhInput" type="number" min="0" step="0.1" value="13.5"></label><label>Est. monthly battery value<input id="batteryMonthlyValueInput" type="number" min="0" value="65"></label><label class="equity-row"><input id="equityEligibleInput" type="checkbox"> Income/equity incentive review</label>`);
let results=$('.results');if(results&&!$('#batteryProgramValue'))results.insertAdjacentHTML('beforeend','<article class="green"><span>Battery/program value</span><strong id="batteryProgramValue">$0</strong></article>');
let chart=$('.chart-wrap');if(chart&&!$('#batteryProgramCard'))chart.insertAdjacentHTML('afterend','<div id="batteryProgramCard" class="panel mini-program"><h3 id="batteryProgramHeadline">Battery strategy</h3><p id="batteryProgramNote" class="muted"></p><p id="batteryUrgency" class="muted urgency-line"></p></div>')
}
function nums(){let p=programs[$('#utilityInput')?.value||'aps'];let batt=$('#batteryInput')?.value==='1';let kwh=Number($('#batteryKwhInput')?.value)||13.5;let monthly=Number($('#batteryMonthlyValueInput')?.value);if(!Number.isFinite(monthly)||monthly<0)monthly=p[3];let equity=$('#equityEligibleInput')?.checked||false;let inc=batt*kwh*(equity&&p[5]?p[5]:p[4]);return{bill:Number($('#billInput')?.value)||0,solar:Number($('#solarInput')?.value)||0,ue:(Number($('#utilityEscInput')?.value)||0)/100,se:(Number($('#solarEscInput')?.value)||0)/100,years:Math.max(1,Math.min(30,Number($('#yearsInput')?.value)||25)),batt,kwh,monthly,inc,p,equity}}
function calc(){let n=nums(),ut=0,st=0,pts=[];for(let y=1;y<=n.years;y++){let u=n.bill*Math.pow(1+n.ue,y-1)*12,s=n.solar*Math.pow(1+n.se,y-1)*12;ut+=u;st+=s;pts.push({u,s})}let bval=n.batt?(n.monthly*12*Math.min(n.years,n.p[6])+n.inc):0;put('currentMonthly',money(n.bill));put('solarMonthly',money(n.solar));put('yearOneSavings',money((n.bill-n.solar)*12+(n.batt?n.monthly*12+n.inc:0)));put('lifetimeSavings',money(ut-st+bval));put('previewBill',money(n.bill));put('previewSavings',money(ut-st+bval).replace('$',''));put('batteryProgramValue',n.batt?money(bval):'$0');put('batteryProgramHeadline',n.p[1]);put('batteryProgramNote',n.p[2]);put('batteryUrgency',n.p[7]);draw(pts);updateAll()}
function draw(pts){let c=$('#savingsCanvas');if(!c)return;let x=c.getContext('2d'),W=c.width,H=c.height,p=46,max=Math.max(...pts.flatMap(o=>[o.u,o.s]),1);x.clearRect(0,0,W,H);x.strokeStyle='rgba(255,255,255,.16)';for(let i=0;i<5;i++){let y=p+i*((H-p*1.5)/4);x.beginPath();x.moveTo(p,y);x.lineTo(W-p,y);x.stroke()}function line(k,col){x.beginPath();pts.forEach((o,i)=>{let xx=p+i/(Math.max(pts.length-1,1))*(W-p*2),yy=H-p-o[k]/max*(H-p*2);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.strokeStyle=col;x.lineWidth=5;x.lineCap='round';x.stroke()}line('u','rgba(255,125,125,.92)');line('s',getComputedStyle(document.documentElement).getPropertyValue('--gold').trim()||'#f4c76b')}
function closeText(){let ps=pains(),survey=val('siteSurveyDate','');return`Based on what you shared, the main goal is ${val('customerGoal','lowering the long-term cost of power')}. Right now ${val('customerName','this home')} is around ${$('#currentMonthly')?.textContent}/month with the utility, and this plan is estimated around ${$('#solarMonthly')?.textContent}/month.\n\nThe biggest priorities we talked about are: ${ps.length?ps.join(', '):'monthly control, utility protection, and a cleaner long-term plan'}.\n\nThe next step is the home survey${survey?` on ${survey}`:''} so the roof, electrical, shade, battery sizing, and final design can be verified before install.`}
function customerText(){let n=nums(),ps=pains(),survey=val('siteSurveyDate','TBD');return`Home energy review${val('customerName')?` for ${val('customerName')}`:''}\n\nWhat we looked at:\n- Main goal: ${val('customerGoal','a more predictable energy plan')}\n- Priorities: ${ps.length?ps.join(', '):'lower cost, predictability, and long-term control'}\n\nEstimated numbers:\n- Current utility bill: ${$('#currentMonthly')?.textContent}/month\n- Estimated solar payment: ${$('#solarMonthly')?.textContent}/month\n- Estimated year 1 difference: ${$('#yearOneSavings')?.textContent}\n- Estimated ${n.years}-year difference: ${$('#lifetimeSavings')?.textContent}\n- Battery/program value shown: ${$('#batteryProgramValue')?.textContent}\n- Backup/battery: ${n.batt?`Included — ${n.kwh} kWh battery review with ${n.p[0]}`:'Not included in this estimate'}\n\nBattery / rate note:\n${n.batt?`${n.p[1]}: ${n.p[2]}`:'Battery storage and rate-arbitrage are not included in this version of the estimate.'}\n\nTimeline:\n- Site survey: ${survey}\n- Design review: usually about 2 weeks after survey\n- Install window: typically 2–4 weeks after design approval\n- Activation: typically 3–4 weeks after install/inspection\n\nWhy move now:\n${n.p[7]}\n\nFinal numbers come from the approved proposal and utility data.\n\n${profile.rep}\n${profile.company}`}
function repText(){let n=nums(),ps=pains();return`Internal rep recap\n\nCustomer: ${val('customerName','Not set')}\nAddress/area: ${val('customerAddress','Not set')}\nSite survey date: ${val('siteSurveyDate','TBD')}\nMain goal: ${val('customerGoal','Not set')}\nPain points/priorities: ${ps.join(', ')||'None selected'}\nConversation notes: ${val('painNotes','None')}\n\nNumbers shown:\n- Current utility bill: ${$('#currentMonthly')?.textContent}/month\n- Estimated solar payment: ${$('#solarMonthly')?.textContent}/month\n- Year 1 difference: ${$('#yearOneSavings')?.textContent}\n- Estimated ${n.years}-year difference: ${$('#lifetimeSavings')?.textContent}\n- Utility increase used: ${(n.ue*100).toFixed(2)}%\n- Solar adjustment used: ${(n.se*100).toFixed(2)}%\n- Utility/program selected: ${n.p[0]} — ${n.p[1]}\n- Battery: ${n.batt?'Included':'Not included'}\n- Battery kWh: ${n.kwh}\n- Est. one-time incentive: ${money(n.inc)}\n- Est. monthly battery value: ${money(n.monthly)}\n\nFollow-up angle:\nTie the next conversation back to ${ps.length?ps.join(', '):'their stated goal and the cost comparison'}. Keep the home survey as the clean next step because program/rate availability and install calendars can change.\n\nRep: ${profile.rep} · ${profile.company}`}
function quoteBar(){let bar=$('.deal-bar'),sum=$('#summaryLine');if(!bar||!sum)return;let n=nums(),parts=[],ps=pains();['customerName','customerAddress','siteSurveyDate'].forEach(id=>{let v=val(id);if(v)parts.push(id==='siteSurveyDate'?`Survey ${v}`:v)});let g=val('customerGoal');if(g)parts.push('Goal: '+(g.length>42?g.slice(0,42)+'...':g));if(ps.length)parts.push(`${ps.length} priorities`);if(touched.has('billInput'))parts.push(`Bill ${$('#currentMonthly')?.textContent}`);if(touched.has('solarInput'))parts.push(`Solar ${$('#solarMonthly')?.textContent}`);if(touched.has('billInput')||touched.has('solarInput')||touched.has('batteryInput')||touched.has('utilityInput'))parts.push(`Difference ${$('#lifetimeSavings')?.textContent}`);if(touched.has('batteryInput')||touched.has('utilityInput'))parts.push(n.batt?`${n.p[0]} battery`:'No battery');sum.textContent=parts.join(' · ');bar.classList.toggle('empty',!parts.length);bar.classList.toggle('has-details',!!parts.length)}
function timeline(){let d=val('siteSurveyDate','TBD'),it=$$('.timeline article');if(it[1])$('p',it[1]).textContent=`Site survey: ${d}. Roof, attic, electrical, shade, and site conditions.`;if(it[2])$('p',it[2]).textContent='Design usually comes back about 2 weeks after survey.';if(it[3])$('p',it[3]).textContent='Install is typically another 2–4 weeks after design approval.';if(it[4])$('p',it[4]).textContent='Activation/PTO is typically 3–4 weeks after install and inspection.'}
function updateAll(){put('closeScript',closeText());put('customerRecapPreview',customerText());put('repRecapPreview',repText());put('previewPains',String(pains().length));timeline();quoteBar()}
function tabs(){document.body.classList.add('tabbed-presentation');let sections=$$('main>section');if(sections[2]&&!sections[2].id)sections[2].id='home-details';let groups={hero:['hero'],discover:['discover','home-details'],money:['money'],solution:['solution'],proof:['proof'],close:['close']},links=$$('.nav a');function show(id){id=groups[id]?id:'hero';sections.forEach(s=>s.classList.add('stage-hidden'));groups[id].forEach(x=>$('#'+x)?.classList.remove('stage-hidden'));links.forEach(a=>a.classList.toggle('active',(a.getAttribute('href')||'').slice(1)===id));history.replaceState(null,'','#'+id);scrollTo({top:0,behavior:'smooth'})}links.forEach(a=>a.onclick=e=>{e.preventDefault();show((a.getAttribute('href')||'#hero').slice(1))});show((location.hash||'#hero').slice(1))}
function copy(t){navigator.clipboard.writeText(t).then(()=>toast('Copied')).catch(()=>toast('Copy failed'))}
function printSnap(){document.body.classList.add('printing-all');setTimeout(()=>print(),80);setTimeout(()=>document.body.classList.remove('printing-all'),1200)}
function bind(){
$('#saveSettings')?.addEventListener('click',saveProfile);$('#openSettings')?.addEventListener('click',()=>$('#settingsPanel')?.classList.add('open'));$('#closeSettings')?.addEventListener('click',()=>$('#settingsPanel')?.classList.remove('open'));$('#resetSettings')?.addEventListener('click',()=>{localStorage.removeItem(store);toast('Reset')});
$('#logoInput')?.addEventListener('change',e=>file(e,'logo'));$('#photoInput')?.addEventListener('change',e=>file(e,'photo'));
['billInput','solarInput','utilityEscInput','solarEscInput','yearsInput','batteryInput','utilityInput','batteryKwhInput','batteryMonthlyValueInput','equityEligibleInput'].forEach(id=>$('#'+id)?.addEventListener('input',()=>{touched.add(id);if(id==='utilityInput')$('#batteryMonthlyValueInput').value=programs[$('#utilityInput').value][3];calc()}));
['customerName','customerAddress','customerGoal','painNotes','siteSurveyDate'].forEach(id=>$('#'+id)?.addEventListener('input',updateAll));$$('#painChecks input').forEach(i=>i.addEventListener('change',updateAll));
['copyCustomerTop','copyCustomerRecap','copyCustomerRecapBottom','copyCustomerFloat'].forEach(id=>$('#'+id)?.addEventListener('click',e=>{e.preventDefault();copy(customerText())},true));
['copyRepRecap','copyRepRecapBottom','copyRepFloat'].forEach(id=>$('#'+id)?.addEventListener('click',e=>{e.preventDefault();copy(repText())},true));$('#printSnapshotButton')?.addEventListener('click',printSnap,true);addEventListener('afterprint',()=>document.body.classList.remove('printing-all'))
}
function file(e,k){let f=e.target.files&&e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{profile[k]=r.result;localStorage.setItem(store,JSON.stringify(profile));applyProfile();toast(k==='logo'?'Logo applied':'Photo applied')};r.readAsDataURL(f)}
injectStyle();addFields();applyProfile();tabs();bind();calc();updateAll();
})();