const $=id=>document.getElementById(id);
const D={name:'Rep Name',company:'UNTD Solar',phone:'',email:'',subtitle:'Solar + battery consultant for homeowners who want clear numbers and a simple explanation.',photo:''};
let photoData='';
const clean=p=>(p||'').replace(/[^0-9+]/g,'');
const initials=n=>(n||'R').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'R';
const first=n=>(n&&n!=='Rep Name'?n.split(/\s+/)[0]:'rep');
const money0=n=>(Number.isFinite(n)?n:0).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const money2=n=>(Number.isFinite(n)?n:0).toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2});
function show(msg){const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function openDrawer(){if(!document.body.classList.contains('locked')){$('drawer').classList.add('open');$('shade').classList.add('open')}}
function closeDrawer(){$('drawer').classList.remove('open');$('shade').classList.remove('open')}
function read(){return{name:$('setName').value.trim()||D.name,company:$('setCompany').value.trim()||D.company,phone:$('setPhone').value.trim()||D.phone,email:$('setEmail').value.trim()||D.email,subtitle:$('setSubtitle').value.trim()||D.subtitle,photo:$('setPhoto').value.trim()||photoData||''}}
function put(c){$('setName').value=c.name==='Rep Name'?'':c.name;$('setCompany').value=c.company==='UNTD Solar'?'UNTD Solar':c.company;$('setPhone').value=c.phone;$('setEmail').value=c.email;$('setSubtitle').value=c.subtitle;$('setPhoto').value=c.photo&&c.photo.startsWith('http')?c.photo:'';photoData=c.photo&&!c.photo.startsWith('http')?c.photo:'';apply()}
function safeHref(kind,value){return value?kind+value:'#'}
function apply(){const c=read(),p=clean(c.phone);$('topInitial').textContent=initials(c.name).slice(0,1);$('topName').textContent=c.name;$('topCompany').textContent=c.company;$('repName').textContent=c.name;$('photoName').textContent=first(c.name);$('photoCompany').textContent=c.company.toUpperCase();$('photoInitials').textContent=initials(c.name);$('badgeCompany').textContent=c.company;$('repSubtitle').textContent=c.subtitle;$('ctaTitle').textContent='Text, call, or email '+first(c.name)+'.';['textBtn','ctaText'].forEach(id=>$(id).href=safeHref('sms:',p));['callBtn','ctaCall'].forEach(id=>$(id).href=safeHref('tel:',p));['emailBtn','ctaEmail'].forEach(id=>$(id).href=safeHref('mailto:',c.email));if(c.photo){$('repPhoto').src=c.photo;$('photoBox').classList.add('has-img')}else{$('repPhoto').removeAttribute('src');$('photoBox').classList.remove('has-img')}}
function lockedUrl(){apply();const u=new URL(location.href),q=new URLSearchParams();u.search='';u.hash='';Object.entries(read()).forEach(([k,v])=>{if(v)q.set(k,v)});u.hash='card='+encodeURIComponent(q.toString());return u.toString()}
function lockCard(){const url=lockedUrl();history.replaceState(null,'',url);document.body.classList.add('locked');closeDrawer();show('Card locked. Tap the photo to share it.')}
function loadImage(src){return new Promise(res=>{if(!src)return res(null);const img=new Image();if(src.startsWith('http'))img.crossOrigin='anonymous';img.onload=()=>res(img);img.onerror=()=>res(null);img.src=src})}
function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function cover(ctx,img,x,y,w,h){const s=Math.max(w/img.width,h/img.height),sw=w/s,sh=h/s,sx=(img.width-sw)/2,sy=(img.height-sh)/2;ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h)}
function toBlob(canvas){return new Promise(res=>canvas.toBlob(res,'image/png'))}
async function buildCardImage(){const c=read(),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=1080;canvas.height=1350;let g=ctx.createLinearGradient(0,0,1080,1350);g.addColorStop(0,'#050506');g.addColorStop(.55,'#111722');g.addColorStop(1,'#050506');ctx.fillStyle=g;ctx.fillRect(0,0,1080,1350);ctx.fillStyle='rgba(214,170,69,.18)';ctx.beginPath();ctx.arc(180,90,360,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(68,200,255,.16)';ctx.beginPath();ctx.arc(920,140,300,0,Math.PI*2);ctx.fill();round(ctx,70,70,940,1210,52);ctx.fillStyle='rgba(255,255,255,.075)';ctx.fill();ctx.strokeStyle='rgba(255,255,255,.18)';ctx.lineWidth=3;ctx.stroke();round(ctx,120,120,840,650,42);ctx.fillStyle='#0b0f14';ctx.fill();ctx.save();round(ctx,120,120,840,650,42);ctx.clip();const im=await loadImage(c.photo);if(im){cover(ctx,im,120,120,840,650)}else{let rg=ctx.createRadialGradient(540,380,30,540,380,380);rg.addColorStop(0,'#ffe29a');rg.addColorStop(1,'#d6aa45');ctx.fillStyle=rg;ctx.fillRect(120,120,840,650);ctx.fillStyle='#140e04';ctx.beginPath();ctx.arc(540,380,170,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f7f4ec';ctx.font='900 110px Inter,Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(initials(c.name),540,380)}ctx.restore();ctx.textAlign='center';ctx.fillStyle='#f7f4ec';ctx.font='900 74px Inter,Arial';ctx.fillText(c.name,540,870);ctx.fillStyle='#ffe29a';ctx.font='900 30px Inter,Arial';ctx.fillText((c.company||'').toUpperCase(),540,925);ctx.fillStyle='rgba(255,255,255,.82)';ctx.font='700 34px Inter,Arial';ctx.fillText('Business card + helpful solar and battery resources',540,1000);ctx.fillStyle='#d6aa45';ctx.font='900 38px Inter,Arial';ctx.fillText(clean(c.phone)||'Phone number',540,1080);ctx.fillStyle='#f7f4ec';ctx.font='800 34px Inter,Arial';ctx.fillText(c.email||'email@example.com',540,1140);ctx.fillStyle='rgba(255,255,255,.58)';ctx.font='700 24px Inter,Arial';ctx.fillText('Text, call, email, view proof links, or run a quick estimate.',540,1210);const blob=await toBlob(canvas);return new File([blob],(c.name||'contact-card').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.png',{type:'image/png'})}
async function shareCard(){if(!location.hash.startsWith('#card='))lockCard();const c=read(),link=location.href,msg='Nice meeting you. Here is my business card with my contact info and a few helpful solar and battery resources.';try{const file=await buildCardImage();if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:c.name+' | '+c.company,text:msg,files:[file]})}else if(navigator.share){await navigator.share({title:c.name+' | '+c.company,text:msg,url:link})}else{await navigator.clipboard.writeText(link);show('Card link copied.')}}catch(e){show('Share cancelled. Tap the photo when ready.')}}
function fileToPhoto(file){const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=520,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);photoData=canvas.toDataURL('image/jpeg',.62);$('setPhoto').value='';apply();$('status').textContent='Photo added. Tap Lock My Card.'};img.src=r.result};r.readAsDataURL(file)}
function load(){const h=location.hash.startsWith('#card=')?decodeURIComponent(location.hash.slice(6)):'';const q=new URLSearchParams(h||location.search);if(q.size){put({name:q.get('name')||D.name,company:q.get('company')||D.company,phone:q.get('phone')||D.phone,email:q.get('email')||D.email,subtitle:q.get('subtitle')||D.subtitle,photo:q.get('photo')||''});document.body.classList.add('locked')}else put(D)}
function calc(){const num=(id,f=0)=>{const n=parseFloat($(id)?.value);return Number.isFinite(n)?n:f};const bill=Math.max(0,num('bill')),solarStart=Math.max(0,num('solarPayment')),yrs=Math.max(1,Math.min(30,parseInt($('yearsRange').value||'25',10))),uEsc=Math.max(0,Math.min(1,num('utilityEsc',.09))),sEsc=Math.max(0,Math.min(1,num('solarEsc',.0299)));let uT=0,sT=0,last=0;for(let y=1;y<=yrs;y++){const u=bill*Math.pow(1+uEsc,y-1),s=solarStart*Math.pow(1+sEsc,y-1);uT+=u*12;sT+=s*12;if(y===yrs)last=u}$('yearsDisplay').textContent=yrs;$('snapYear').textContent=yrs;$('utilTotal').textContent=money0(uT);$('solarTotal').textContent=money0(sT);$('differenceLabel').textContent=money0(uT-sT);$('selMonthlyUtility').textContent=money2(last)}
document.addEventListener('DOMContentLoaded',()=>{$('openMenu').onclick=openDrawer;$('closeMenu').onclick=closeDrawer;$('shade').onclick=closeDrawer;$('lockCard').onclick=lockCard;$('photoBox').onclick=shareCard;$('photoBox').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();shareCard()}};$('setUpload').onchange=e=>{const f=e.target.files&&e.target.files[0];if(f)fileToPhoto(f)};['setName','setCompany','setPhone','setEmail','setSubtitle','setPhoto'].forEach(id=>$(id).addEventListener('input',apply));$('year').textContent=new Date().getFullYear();load();['bill','solarPayment','yearsRange','solarEsc'].forEach(id=>{const el=$(id);el.addEventListener('input',calc);el.addEventListener('change',calc)});$('savingsForm').onsubmit=e=>{e.preventDefault();calc()};calc()});
